import * as mc from "./elements.js"

export type IntelliSense = {
	achievement: mc.Achievement
	add_external_server: mc.AddExternalServer
	adhoc_inprogress: mc.AdhocInprogress
	adhoc: mc.Adhoc
	anvil: mc.Anvil
	anvil_pocket: mc.AnvilPocket
	authentication_modals: mc.AuthenticationModals
	authentication: mc.Authentication
	auto_save_info: mc.AutoSaveInfo
	beacon: mc.Beacon
	beacon_pocket: mc.BeaconPocket
	blast_furnace: mc.BlastFurnace
	book: mc.Book
	brewing_stand: mc.BrewingStand
	brewing_stand_pocket: mc.BrewingStandPocket
	bundle_purchase_warning: mc.BundlePurchaseWarning
	cartography: mc.Cartography
	cartography_pocket: mc.CartographyPocket
	chalkboard: mc.Chalkboard
	chat: mc.Chat
	chat_settings: mc.ChatSettings
	chest: mc.Chest
	choose_realm: mc.ChooseRealm
	coin_purchase: mc.CoinPurchase
	command_block: mc.CommandBlock
	confirm_delete_account: mc.ConfirmDeleteAccount
	content_log: mc.ContentLog
	content_log_history: mc.ContentLogHistory
	crafter_pocket: mc.CrafterPocket
	create_world_upsell: mc.CreateWorldUpsell
	credits: mc.Credits
	csb_purchase_error: mc.CsbPurchaseError
	csb: mc.Csb
	csb_content: mc.CsbContent
	csb_banner: mc.CsbBanner
	csb_buy: mc.CsbBuy
	common_csb: mc.CommonCsb
	csb_purchase_amazondevicewarning: mc.CsbPurchaseAmazondevicewarning
	csb_purchase_warning: mc.CsbPurchaseWarning
	csb_subscription_panel: mc.CsbSubscriptionPanel
	csb_upsell: mc.CsbUpsell
	csb_packs: mc.CsbPacks
	csb_welcome: mc.CsbWelcome
	csb_faq: mc.CsbFaq
	csb_landing: mc.CsbLanding
	custom_templates: mc.CustomTemplates
	world_conversion_complete: mc.WorldConversionComplete
	day_one_experience_intro: mc.DayOneExperienceIntro
	day_one_experience: mc.DayOneExperience
	death: mc.Death
	debug_screen: mc.DebugScreen
	dev_console: mc.DevConsole
	disconnect: mc.Disconnect
	display_logged_error: mc.DisplayLoggedError
	discovery_dialog: mc.DiscoveryDialog
	edu_featured: mc.EduFeatured
	edu_quit_button: mc.EduQuitButton
	persona_emote: mc.PersonaEmote
	enchanting: mc.Enchanting
	enchanting_pocket: mc.EnchantingPocket
	encyclopedia: mc.Encyclopedia
	expanded_skin_pack: mc.ExpandedSkinPack
	feed_common: mc.FeedCommon
	file_upload: mc.FileUpload
	furnace: mc.Furnace
	furnace_pocket: mc.FurnacePocket
	game_tip: mc.GameTip
	gamepad_disconnected: mc.GamepadDisconnected
	gameplay: mc.Gameplay
	gathering_info: mc.GatheringInfo
	globalpause: mc.Globalpause
	grindstone: mc.Grindstone
	grindstone_pocket: mc.GrindstonePocket
	gamma_calibration: mc.GammaCalibration
	horse: mc.Horse
	horse_pocket: mc.HorsePocket
	how_to_play_common: mc.HowToPlayCommon
	how_to_play: mc.HowToPlay
	hud: mc.Hud
	host_options: mc.HostOptions
	bed: mc.Bed
	im_reader: mc.ImReader
	crafting: mc.Crafting
	crafting_pocket: mc.CraftingPocket
	invite: mc.Invite
	jigsaw_editor: mc.JigsawEditor
	late_join: mc.LateJoin
	library_modal: mc.LibraryModal
	local_world_picker: mc.LocalWorldPicker
	loom: mc.Loom
	loom_pocket: mc.LoomPocket
	manage_feed: mc.ManageFeed
	manifest_validation: mc.ManifestValidation
	sdl_label: mc.SdlLabel
	sdl_dropdowns: mc.SdlDropdowns
	sdl_image_row: mc.SdlImageRow
	sdl_text_row: mc.SdlTextRow
	mob_effect: mc.MobEffect
	non_xbl_user_management: mc.NonXblUserManagement
	npc_interact: mc.NpcInteract
	online_safety: mc.OnlineSafety
	pack_settings: mc.PackSettings
	panorama: mc.Panorama
	patch_notes: mc.PatchNotes
	pause: mc.Pause
	pdp: mc.Pdp
	pdp_screenshots: mc.PdpScreenshots
	permissions: mc.Permissions
	persona_cast_character_screen: mc.PersonaCastCharacterScreen
	persona_common: mc.PersonaCommon
	persona_popups: mc.PersonaPopups
	play: mc.Play
	perf_turtle: mc.PerfTurtle
	pocket_containers: mc.PocketContainers
	popup_dialog: mc.PopupDialog
	portfolio: mc.Portfolio
	progress: mc.Progress
	rating_prompt: mc.RatingPrompt
	realms_common: mc.RealmsCommon
	realms_create: mc.RealmsCreate
	realms_pending_invitations: mc.RealmsPendingInvitations
	realms_slots: mc.RealmsSlots
	realms_settings: mc.RealmsSettings
	realms_allowlist: mc.RealmsAllowlist
	realms_invite_link_settings: mc.RealmsInviteLinkSettings
	realms_plus_ended: mc.RealmsPlusEnded
	realmsPlus: mc.RealmsPlus
	realmsPlus_content: mc.RealmsPlusContent
	realmsPlus_faq: mc.RealmsPlusFaq
	realmsPlus_landing: mc.RealmsPlusLanding
	realmsPlus_buy: mc.RealmsPlusBuy
	realmsPlus_packs: mc.RealmsPlusPacks
	realmsPlus_purchase_warning: mc.RealmsPlusPurchaseWarning
	realms_stories_transition: mc.RealmsStoriesTransition
	redstone: mc.Redstone
	resource_packs: mc.ResourcePacks
	safe_zone: mc.SafeZone
	storage_migration_common: mc.StorageMigrationCommon
	storage_migration_generic: mc.StorageMigrationGeneric
	scoreboard: mc.Scoreboard
	screenshot: mc.Screenshot
	select_world: mc.SelectWorld
	server_form: mc.ServerForm
	settings: mc.Settings
	controls_section: mc.ControlsSection
	general_section: mc.GeneralSection
	realms_world_section: mc.RealmsWorldSection
	settings_common: mc.SettingsCommon
	world_section: mc.WorldSection
	social_section: mc.SocialSection
	sidebar_navigation: mc.SidebarNavigation
	sign: mc.Sign
	simple_inprogress: mc.SimpleInprogress
	skin_pack_purchase: mc.SkinPackPurchase
	skin_picker: mc.SkinPicker
	smithing_table: mc.SmithingTable
	smithing_table_2: mc.SmithingTable2
	smithing_table_pocket: mc.SmithingTablePocket
	smithing_table_2_pocket: mc.SmithingTable2Pocket
	smoker: mc.Smoker
	start: mc.Start
	stonecutter: mc.Stonecutter
	stonecutter_pocket: mc.StonecutterPocket
	storage_management: mc.StorageManagement
	storage_management_popup: mc.StorageManagementPopup
	common_store: mc.CommonStore
	store_layout: mc.StoreLayout
	filter_menu: mc.FilterMenu
	store_inventory: mc.StoreInventory
	store_item_list: mc.StoreItemList
	store_progress: mc.StoreProgress
	promo_timeline: mc.PromoTimeline
	store_sale_item_list: mc.StoreSaleItemList
	store_search: mc.StoreSearch
	sort_menu: mc.SortMenu
	structure_editor: mc.StructureEditor
	submit_feedback: mc.SubmitFeedback
	tabbed_upsell: mc.TabbedUpsell
	thanks_for_testing: mc.ThanksForTesting
	third_party_store: mc.ThirdPartyStore
	toast_screen: mc.ToastScreen
	token_faq: mc.TokenFaq
	trade: mc.Trade
	trade_pocket: mc.TradePocket
	trade2: mc.Trade2
	trade2_pocket: mc.Trade2Pocket
	trialUpsell: mc.TrialUpsell
	ugc_viewer: mc.UgcViewer
	common_art: mc.CommonArt
	common: mc.Common
	"common-classic": mc.CommonClassic
	edu_common: mc.EduCommon
	purchase_common: mc.PurchaseCommon
	common_buttons: mc.CommonButtons
	common_dialogs: mc.CommonDialogs
	common_tabs: mc.CommonTabs
	common_toggles: mc.CommonToggles
	friendsbutton: mc.Friendsbutton
	iconbutton: mc.Iconbutton
	update_dimensions: mc.UpdateDimensions
	update_version: mc.UpdateVersion
	world_recovery: mc.WorldRecovery
	world_templates: mc.WorldTemplates
	xbl_console_qr_signin: mc.XblConsoleQrSignin
	xbl_console_signin: mc.XblConsoleSignin
	xbl_console_signin_succeeded: mc.XblConsoleSigninSucceeded
	xbl_immediate_signin: mc.XblImmediateSignin
	win10_trial_conversion: mc.Win10TrialConversion
}
