export enum Links {
    PROPERTY_BAG = "unset #hyperlink in property_bag",
    EULA = "http://education.minecraft.net/eula",
    HTML = "http://pocketbeta.minecraft.net/p/how-to-join-and-leave-beta.html",
    MINECRAFTREALMSFB = "http://aka.ms/minecraftrealmsfb",
    MINECRAFTREALMSTERMS = "http://aka.ms/minecraftrealmsterms",
    MINECRAFTFB = "http://aka.ms/minecraftfb",
    MINECRAFTEDUSUPPORT = "http://aka.ms/minecraftedusupport",
    BLOCKXBOXMESSAGES = "https://aka.ms/blockxboxmessages",
    MINECRAFTFBBETA = "http://aka.ms/minecraftfbbeta",
    ATTRIBUTION = "https://minecraft.net/attribution",
    MCEDULOGS = "http://aka.ms/mcedulogs",
    EULA_1 = "https://education.minecraft.net/eula",
    MCEDULOGS_1 = "https://aka.ms/mcedulogs",
    MINECRAFTREALMSTERMS_1 = "https://aka.ms/minecraftrealmsterms",
    MINECRAFTFB_1 = "https://aka.ms/minecraftfb",
    MINECRAFTFBBETA_1 = "https://aka.ms/minecraftfbbeta",
    MINECRAFTEDUSUPPORT_1 = "https://aka.ms/minecraftedusupport",
    _8 = "https://itunes.apple.com/us/app/minecraft/id479516143?mt=8",
    SETTINGS = "https://account.xbox.com/Settings",
    MEETERMS = "https://aka.ms/meeterms",
    PRIVACY = "https://aka.ms/privacy",
    MCBANNED = "https://aka.ms/MCBanned",
    MCMULTIPLAYERHELP = "https://aka.ms/MCMultiplayerHelp",
    MEEEULA = "https://aka.ms/meeeula",
    MEE_PRIVACY = "https://aka.ms/mee_privacy",
    HIDECHROME = "https://www.minecraft.net/attribution/?hideChrome",
    SWITCHATTRIBUTION = "https://aka.ms/switchattribution",
    HIDECHROME_1 = "https://www.minecraft.net/licensed-content/?hideChrome",
    SWITCHCONTENT = "https://aka.ms/switchcontent",
    CHANGEGAMERTAG = "https://social.xbox.com/changegamertag",
}